### ISSUE TITLE
Protocol Buffer specs are out of date.

### ISSUE THREAD

**Issue by brianedgerton** [nlf/riakproto#5]
Hi Nathan,

First of all, thanks for this awesome library. We are currently using it under the hood of our [Riaktive](https://github.com/LeanKit-Labs/riaktive) library here at LeanKit. We have run into an issue after upgrading our Riak version to 2.1. To make a long story short, we were getting an "unknown message" error when requesting bucket properties. After a lot of digging, we have discovered that there was an addition to the protocol buffer spec for `RpbBucketProps`. There is now an added `optional bool write_once = 28;` property.

We were able come up with a solution by updating the `riak_pb` submodule here in `riakproto`. Is this something you would be able to update and release? The latest tagged release for `riak_pb` is here:

[https://github.com/basho/riak_pb/commit/620bc7001dc788e5530078aa8be53c9d15d4fdb4](https://github.com/basho/riak_pb/commit/620bc7001dc788e5530078aa8be53c9d15d4fdb4)

You can see the new property addition in that PR. What are your thoughts on this?

Thanks!

**Comment by nlf** [comment]
closed by #6
